struct PhilosopherQuote {
    let text: String
    let author: String
}

struct QuoteCollection {
    static let quotes: [PhilosopherQuote] = [
        // Marcus Aurelius
        PhilosopherQuote(text: "Waste no more time arguing about what a good man should be. Be one.", author: "Marcus Aurelius"),
        PhilosopherQuote(text: "Very little is needed to make a happy life; it is all within yourself, in your way of thinking.", author: "Marcus Aurelius"),
        PhilosopherQuote(text: "The happiness of your life depends upon the quality of your thoughts.", author: "Marcus Aurelius"),
        PhilosopherQuote(text: "When you arise in the morning, think of what a precious privilege it is to be alive - to breathe, to think, to enjoy, to love.", author: "Marcus Aurelius"),
        PhilosopherQuote(text: "Accept the things to which fate binds you, and love the people with whom fate brings you together.", author: "Marcus Aurelius"),
        PhilosopherQuote(text: "You have power over your mind - not outside events. Realize this, and you will find strength.", author: "Marcus Aurelius"),
        PhilosopherQuote(text: "The best revenge is to be unlike him who performed the injury.", author: "Marcus Aurelius"),
        PhilosopherQuote(text: "Everything we hear is an opinion, not a fact. Everything we see is a perspective, not the truth.", author: "Marcus Aurelius"),
        PhilosopherQuote(text: "If you are distressed by anything external, the pain is not due to the thing itself, but to your estimate of it; and this you have the power to revoke at any moment.", author: "Marcus Aurelius"),
        PhilosopherQuote(text: "Our life is what our thoughts make it.", author: "Marcus Aurelius"),
        
        // Additional Marcus Aurelius quotes
        PhilosopherQuote(text: "Look well into thyself; there is a source of strength which will always spring up if thou wilt always look.", author: "Marcus Aurelius"),
        PhilosopherQuote(text: "The soul becomes dyed with the color of its thoughts.", author: "Marcus Aurelius"),
        PhilosopherQuote(text: "Never let the future disturb you. You will meet it, if you have to, with the same weapons of reason which today arm you against the present.", author: "Marcus Aurelius"),
        PhilosopherQuote(text: "The object of life is not to be on the side of the majority, but to escape finding oneself in the ranks of the insane.", author: "Marcus Aurelius"),
        PhilosopherQuote(text: "Do every act of your life as though it were the very last act of your life.", author: "Marcus Aurelius"),
        PhilosopherQuote(text: "The first rule is to keep an untroubled spirit. The second is to look things in the face and know them for what they are.", author: "Marcus Aurelius"),
        PhilosopherQuote(text: "How much time he gains who does not look to see what his neighbor says or does or thinks, but only at what he does himself, to make it just and holy.", author: "Marcus Aurelius"),
        PhilosopherQuote(text: "Look beneath the surface; let not the several quality of a thing nor its worth escape thee.", author: "Marcus Aurelius"),
        PhilosopherQuote(text: "The universe is change; our life is what our thoughts make it.", author: "Marcus Aurelius"),
        PhilosopherQuote(text: "Reject your sense of injury and the injury itself disappears.", author: "Marcus Aurelius"),
        PhilosopherQuote(text: "What stands in the way becomes the way.", author: "Marcus Aurelius"),
        PhilosopherQuote(text: "Life is neither good or evil, but only a place for good and evil.", author: "Marcus Aurelius"),
        PhilosopherQuote(text: "The impediment to action advances action. What stands in the way becomes the way.", author: "Marcus Aurelius"),
        PhilosopherQuote(text: "Each day provides its own gifts.", author: "Marcus Aurelius"),
        PhilosopherQuote(text: "Loss is nothing else but change, and change is Nature's delight.", author: "Marcus Aurelius"),
        PhilosopherQuote(text: "Nothing has such power to broaden the mind as the ability to investigate systematically and truly all that comes under thy observation in life.", author: "Marcus Aurelius"),
        PhilosopherQuote(text: "Begin each day by telling yourself: Today I shall be meeting with interference, ingratitude, insolence, disloyalty, ill-will, and selfishness.", author: "Marcus Aurelius"),
        PhilosopherQuote(text: "The art of living is more like wrestling than dancing.", author: "Marcus Aurelius"),
        PhilosopherQuote(text: "Confine yourself to the present.", author: "Marcus Aurelius"),
        PhilosopherQuote(text: "Be tolerant with others and strict with yourself.", author: "Marcus Aurelius"),
        PhilosopherQuote(text: "Life is short. That's all there is to say. Get what you can from the present—thoughtfully, justly.", author: "Marcus Aurelius"),
        PhilosopherQuote(text: "The best answer to anger is silence.", author: "Marcus Aurelius"),
        PhilosopherQuote(text: "To live happily is an inward power of the soul.", author: "Marcus Aurelius"),
        PhilosopherQuote(text: "The memory of everything is very soon overwhelmed in time.", author: "Marcus Aurelius"),
        PhilosopherQuote(text: "Look back over the past, with its changing empires that rose and fell, and you can foresee the future too.", author: "Marcus Aurelius"),
        
        // Epictetus
        PhilosopherQuote(text: "It's not what happens to you, but how you react to it that matters.", author: "Epictetus"),
        PhilosopherQuote(text: "First say to yourself what you would be; then do what you have to do.", author: "Epictetus"),
        PhilosopherQuote(text: "Wealth consists not in having great possessions, but in having few wants.", author: "Epictetus"),
        PhilosopherQuote(text: "Don't explain your philosophy. Embody it.", author: "Epictetus"),
        PhilosopherQuote(text: "There is only one way to happiness and that is to cease worrying about things which are beyond the power of our will.", author: "Epictetus"),
        PhilosopherQuote(text: "No man is free who is not master of himself.", author: "Epictetus"),
        PhilosopherQuote(text: "He who laughs at himself never runs out of things to laugh at.", author: "Epictetus"),
        PhilosopherQuote(text: "If you want to improve, be content to be thought foolish and stupid.", author: "Epictetus"),
        PhilosopherQuote(text: "The key is to keep company only with people who uplift you, whose presence calls forth your best.", author: "Epictetus"),
        PhilosopherQuote(text: "Freedom is the only worthy goal in life. It is won by disregarding things that lie beyond our control.", author: "Epictetus"),
        
        // Additional Epictetus quotes
        PhilosopherQuote(text: "Any person capable of angering you becomes your master.", author: "Epictetus"),
        PhilosopherQuote(text: "Men are disturbed not by things, but by the views which they take of them.", author: "Epictetus"),
        PhilosopherQuote(text: "Only the educated are free.", author: "Epictetus"),
        PhilosopherQuote(text: "It is impossible for a man to learn what he thinks he already knows.", author: "Epictetus"),
        PhilosopherQuote(text: "The greater the difficulty, the more glory in surmounting it.", author: "Epictetus"),
        PhilosopherQuote(text: "No great thing is created suddenly.", author: "Epictetus"),
        PhilosopherQuote(text: "Make the best use of what is in your power, and take the rest as it happens.", author: "Epictetus"),
        PhilosopherQuote(text: "If anyone tells you that a certain person speaks ill of you, do not make excuses about what is said of you but answer, 'He was ignorant of my other faults, else he would not have mentioned these alone.'", author: "Epictetus"),
        PhilosopherQuote(text: "Circumstances don't make the man, they only reveal him to himself.", author: "Epictetus"),
        PhilosopherQuote(text: "Don't seek to have events happen as you wish, but wish them to happen as they do happen, and all will be well with you.", author: "Epictetus"),
        PhilosopherQuote(text: "Know, first, who you are, and then adorn yourself accordingly.", author: "Epictetus"),
        PhilosopherQuote(text: "Small-minded people blame others. Average people blame themselves. The wise see all blame as foolishness.", author: "Epictetus"),
        PhilosopherQuote(text: "If you want to improve, be content to be thought foolish and stupid.", author: "Epictetus"),
        PhilosopherQuote(text: "The essence of philosophy is that a man should so live that his happiness shall depend as little as possible on external things.", author: "Epictetus"),
        PhilosopherQuote(text: "First learn the meaning of what you say, and then speak.", author: "Epictetus"),
        PhilosopherQuote(text: "If anyone tells you that a certain person speaks ill of you, do not make excuses about what is said of you but answer, 'He was ignorant of my other faults, else he would not have mentioned these alone.'", author: "Epictetus"),
        PhilosopherQuote(text: "If you wish to be good, first believe that you are bad.", author: "Epictetus"),
        PhilosopherQuote(text: "Seek not the good in external things; seek it in yourselves.", author: "Epictetus"),
        PhilosopherQuote(text: "If evil be spoken of you and it be true, correct yourself, if it be a lie, laugh at it.", author: "Epictetus"),
        PhilosopherQuote(text: "It is better to die of hunger having lived without grief and fear, than to live with a troubled spirit, amid abundance.", author: "Epictetus"),
        
        // Aristotle
        PhilosopherQuote(text: "Excellence is never an accident. It is always the result of high intention, sincere effort, and intelligent execution.", author: "Aristotle"),
        PhilosopherQuote(text: "We are what we repeatedly do. Excellence, then, is not an act, but a habit.", author: "Aristotle"),
        PhilosopherQuote(text: "Happiness depends upon ourselves.", author: "Aristotle"),
        PhilosopherQuote(text: "The educated differ from the uneducated as much as the living differ from the dead.", author: "Aristotle"),
        PhilosopherQuote(text: "It is during our darkest moments that we must focus to see the light.", author: "Aristotle"),
        PhilosopherQuote(text: "Pleasure in the job puts perfection in the work.", author: "Aristotle"),
        PhilosopherQuote(text: "The whole is greater than the sum of its parts.", author: "Aristotle"),
        PhilosopherQuote(text: "The energy of the mind is the essence of life.", author: "Aristotle"),
        PhilosopherQuote(text: "The aim of art is to represent not the outward appearance of things, but their inward significance.", author: "Aristotle"),
        PhilosopherQuote(text: "Hope is a waking dream.", author: "Aristotle"),
        
        // Additional Aristotle quotes
        PhilosopherQuote(text: "The roots of education are bitter, but the fruit is sweet.", author: "Aristotle"),
        PhilosopherQuote(text: "The worst form of inequality is to try to make unequal things equal.", author: "Aristotle"),
        PhilosopherQuote(text: "Quality is not an act, it is a habit.", author: "Aristotle"),
        PhilosopherQuote(text: "The law is reason, free from passion.", author: "Aristotle"),
        PhilosopherQuote(text: "All men by nature desire knowledge.", author: "Aristotle"),
        PhilosopherQuote(text: "The more you know, the more you know you don't know.", author: "Aristotle"),
        PhilosopherQuote(text: "Character may almost be called the most effective means of persuasion.", author: "Aristotle"),
        PhilosopherQuote(text: "Those who educate children well are more to be honored than they who produce them.", author: "Aristotle"),
        PhilosopherQuote(text: "Dignity does not consist in possessing honors, but in deserving them.", author: "Aristotle"),
        PhilosopherQuote(text: "The ideal man bears the accidents of life with dignity and grace, making the best of circumstances.", author: "Aristotle"),
        PhilosopherQuote(text: "Knowing yourself is the beginning of all wisdom.", author: "Aristotle"),
        PhilosopherQuote(text: "It is the mark of an educated mind to be able to entertain a thought without accepting it.", author: "Aristotle"),
        PhilosopherQuote(text: "No great mind has ever existed without a touch of madness.", author: "Aristotle"),
        PhilosopherQuote(text: "Patience is bitter, but its fruit is sweet.", author: "Aristotle"),
        PhilosopherQuote(text: "Those who know, do. Those that understand, teach.", author: "Aristotle"),
        PhilosopherQuote(text: "To avoid criticism say nothing, do nothing, be nothing.", author: "Aristotle"),
        PhilosopherQuote(text: "The antidote for fifty enemies is one friend.", author: "Aristotle"),
        PhilosopherQuote(text: "The high-minded man must care more for the truth than for what people think.", author: "Aristotle"),
        PhilosopherQuote(text: "The more you know, the more you realize you don't know.", author: "Aristotle"),
        PhilosopherQuote(text: "The wise man does not expose himself needlessly to danger, since there are few things for which he cares sufficiently.", author: "Aristotle"),
        PhilosopherQuote(text: "The young are permanently in a state resembling intoxication.", author: "Aristotle"),
        PhilosopherQuote(text: "Youth is easily deceived because it is quick to hope.", author: "Aristotle"),
        PhilosopherQuote(text: "Wit is educated insolence.", author: "Aristotle"),
        PhilosopherQuote(text: "What is a friend? A single soul dwelling in two bodies.", author: "Aristotle"),
        PhilosopherQuote(text: "The greatest virtues are those which are most useful to other persons.", author: "Aristotle"),
        
        // Socrates
        PhilosopherQuote(text: "The unexamined life is not worth living.", author: "Socrates"),
        PhilosopherQuote(text: "I know that I am intelligent, because I know that I know nothing.", author: "Socrates"),
        PhilosopherQuote(text: "Be kind, for everyone you meet is fighting a hard battle.", author: "Socrates"),
        PhilosopherQuote(text: "Strong minds discuss ideas, average minds discuss events, weak minds discuss people.", author: "Socrates"),
        PhilosopherQuote(text: "By all means marry; if you get a good wife, you'll become happy; if you get a bad one, you'll become a philosopher.", author: "Socrates"),
        PhilosopherQuote(text: "Education is the kindling of a flame, not the filling of a vessel.", author: "Socrates"),
        PhilosopherQuote(text: "To find yourself, think for yourself.", author: "Socrates"),
        PhilosopherQuote(text: "Wonder is the beginning of wisdom.", author: "Socrates"),
        PhilosopherQuote(text: "Let him who would move the world first move himself.", author: "Socrates"),
        PhilosopherQuote(text: "The secret of happiness, you see, is not found in seeking more, but in developing the capacity to enjoy less.", author: "Socrates"),
        
        // Additional Socrates quotes
        PhilosopherQuote(text: "False words are not only evil in themselves, but they infect the soul with evil.", author: "Socrates"),
        PhilosopherQuote(text: "The only true wisdom is in knowing you know nothing.", author: "Socrates"),
        PhilosopherQuote(text: "An honest man is always a child.", author: "Socrates"),
        PhilosopherQuote(text: "The greatest way to live with honor in this world is to be what we pretend to be.", author: "Socrates"),
        PhilosopherQuote(text: "The unexamined life is not worth living for a human being.", author: "Socrates"),
        PhilosopherQuote(text: "I cannot teach anybody anything. I can only make them think.", author: "Socrates"),
        PhilosopherQuote(text: "There is only one good, knowledge, and one evil, ignorance.", author: "Socrates"),
        PhilosopherQuote(text: "He who is not contented with what he has, would not be contented with what he would like to have.", author: "Socrates"),
        PhilosopherQuote(text: "The way to gain a good reputation is to endeavor to be what you desire to appear.", author: "Socrates"),
        PhilosopherQuote(text: "Remember that there is nothing stable in human affairs; therefore avoid undue elation in prosperity, or undue depression in adversity.", author: "Socrates"),
        PhilosopherQuote(text: "Be slow to fall into friendship, but when you are in, continue firm and constant.", author: "Socrates"),
        PhilosopherQuote(text: "Sometimes you put walls up not to keep people out, but to see who cares enough to break them down.", author: "Socrates"),
        PhilosopherQuote(text: "The secret of change is to focus all of your energy, not on fighting the old, but on building the new.", author: "Socrates"),

        // More Socrates quotes
        PhilosopherQuote(text: "The children now love luxury; they have bad manners, contempt for authority; they show disrespect for elders and love chatter in place of exercise.", author: "Socrates"),
        PhilosopherQuote(text: "Wisdom begins in wonder.", author: "Socrates"),
        PhilosopherQuote(text: "The hour of departure has arrived, and we go our separate ways, I to die, and you to live. Which of these two is better only God knows.", author: "Socrates"),
        PhilosopherQuote(text: "Once made equal to man, woman becomes his superior.", author: "Socrates"),
        PhilosopherQuote(text: "From the deepest desires often come the deadliest hate.", author: "Socrates"),
        PhilosopherQuote(text: "The only good is knowledge and the only evil is ignorance.", author: "Socrates"),
        PhilosopherQuote(text: "Life contains but two tragedies. One is not to get your heart's desire; the other is to get it.", author: "Socrates"),
        PhilosopherQuote(text: "To know, is to know that you know nothing. That is the meaning of true knowledge.", author: "Socrates"),
        PhilosopherQuote(text: "Beauty is a short-lived tyranny.", author: "Socrates"),
        PhilosopherQuote(text: "The beginning of wisdom is the definition of terms.", author: "Socrates"),
        PhilosopherQuote(text: "Not life, but good life, is to be chiefly valued.", author: "Socrates"),
        PhilosopherQuote(text: "True wisdom comes to each of us when we realize how little we understand about life, ourselves, and the world around us.", author: "Socrates"),

        // More Marcus Aurelius quotes
        PhilosopherQuote(text: "You must build up your life action by action, and be content if each one achieves its goal as far as possible.", author: "Marcus Aurelius"),
        PhilosopherQuote(text: "The first step: Don't be anxious. Nature controls it all.", author: "Marcus Aurelius"),
        PhilosopherQuote(text: "Just that you do the right thing. The rest doesn't matter.", author: "Marcus Aurelius"),
        PhilosopherQuote(text: "Concentrate every minute like a Roman—like a man—on doing what's in front of you with precise and genuine seriousness.", author: "Marcus Aurelius"),
        PhilosopherQuote(text: "When jarred, unavoidably, by circumstances, revert at once to yourself, and don't lose the rhythm more than you can help.", author: "Marcus Aurelius"),
        PhilosopherQuote(text: "In a word, if there is a god, all is well; and if chance rules, do not also be governed by it.", author: "Marcus Aurelius"),
        PhilosopherQuote(text: "The mind adapts and converts to its own purposes the obstacle to our acting.", author: "Marcus Aurelius"),
        PhilosopherQuote(text: "Choose not to be harmed—and you won't feel harmed. Don't feel harmed—and you haven't been.", author: "Marcus Aurelius"),
        PhilosopherQuote(text: "External things are not the problem. It's your assessment of them. Which you can erase right now.", author: "Marcus Aurelius"),
        PhilosopherQuote(text: "If it is not right, do not do it, if it is not true, do not say it.", author: "Marcus Aurelius"),

        // More Epictetus quotes
        PhilosopherQuote(text: "The greater the difficulty, the more glory in surmounting it.", author: "Epictetus"),
        PhilosopherQuote(text: "Practice yourself, for heaven's sake, in little things; and thence proceed to greater.", author: "Epictetus"),
        PhilosopherQuote(text: "Difficulties are things that show a person what they are.", author: "Epictetus"),
        PhilosopherQuote(text: "If thy brother wrongs thee, remember not so much his wrong-doing, but more than ever that he is thy brother.", author: "Epictetus"),
        PhilosopherQuote(text: "No great thing is created suddenly.", author: "Epictetus"),
        PhilosopherQuote(text: "It is not death or pain that is to be dreaded, but the fear of pain or death.", author: "Epictetus"),
        PhilosopherQuote(text: "If one oversteps the bounds of moderation, the greatest pleasures cease to please.", author: "Epictetus"),
        PhilosopherQuote(text: "We have two ears and one mouth so that we can listen twice as much as we speak.", author: "Epictetus"),
        PhilosopherQuote(text: "A ship should not ride on a single anchor, nor life on a single hope.", author: "Epictetus"),
        PhilosopherQuote(text: "The world turns aside to let any man pass who knows where he is going.", author: "Epictetus"),

        // More Aristotle quotes
        PhilosopherQuote(text: "Anybody can become angry - that is easy, but to be angry with the right person and to the right degree and at the right time and for the right purpose, and in the right way - that is not within everybody's power and is not easy.", author: "Aristotle"),
        PhilosopherQuote(text: "Courage is the first of human qualities because it is the quality which guarantees the others.", author: "Aristotle"),
        PhilosopherQuote(text: "The one exclusive sign of thorough knowledge is the power of teaching.", author: "Aristotle"),
        PhilosopherQuote(text: "All human actions have one or more of these seven causes: chance, nature, compulsion, habit, reason, passion, and desire.", author: "Aristotle"),
        PhilosopherQuote(text: "The least initial deviation from the truth is multiplied later a thousandfold.", author: "Aristotle"),
        PhilosopherQuote(text: "Nature does nothing uselessly.", author: "Aristotle"),
        PhilosopherQuote(text: "The actuality of thought is life.", author: "Aristotle"),
        PhilosopherQuote(text: "Change in all things is sweet.", author: "Aristotle"),
        PhilosopherQuote(text: "In all things of nature there is something of the marvelous.", author: "Aristotle"),
        PhilosopherQuote(text: "Personal beauty is a greater recommendation than any letter of reference.", author: "Aristotle"),

        // More Socrates quotes
        PhilosopherQuote(text: "The only good is knowledge and the only evil is ignorance.", author: "Socrates"),
        PhilosopherQuote(text: "The greatest blessing granted to mankind come by way of madness, which is a divine gift.", author: "Socrates"),
        PhilosopherQuote(text: "One should never do wrong in return, nor mistreat any man, no matter how one has been mistreated by him.", author: "Socrates"),
        PhilosopherQuote(text: "The nearest way to glory is to strive to be what you wish to be thought to be.", author: "Socrates"),
        PhilosopherQuote(text: "Think not those faithful who praise all thy words and actions, but those who kindly reprove thy faults.", author: "Socrates"),
        PhilosopherQuote(text: "The end of life is to be like God, and the soul following God will be like Him.", author: "Socrates"),
        PhilosopherQuote(text: "Nature has given us two ears, two eyes, and but one tongue-to the end that we should hear and see more than we speak.", author: "Socrates"),
        PhilosopherQuote(text: "Call no man unhappy until he is married.", author: "Socrates"),
        PhilosopherQuote(text: "Employ your time in improving yourself by other men's writings so that you shall come easily by what others have labored hard for.", author: "Socrates"),
        PhilosopherQuote(text: "The way to gain a good reputation is to endeavor to be what you desire to appear.", author: "Socrates"),

        // More Confucius quotes
        PhilosopherQuote(text: "Choose a job you love, and you will never have to work a day in your life.", author: "Confucius"),
        PhilosopherQuote(text: "The strength of a nation derives from the integrity of the home.", author: "Confucius"),
        PhilosopherQuote(text: "When anger rises, think of the consequences.", author: "Confucius"),
        PhilosopherQuote(text: "He who learns but does not think, is lost. He who thinks but does not learn is in great danger.", author: "Confucius"),
        PhilosopherQuote(text: "What you do not want done to yourself, do not do to others.", author: "Confucius"),
        PhilosopherQuote(text: "Success depends upon previous preparation, and without such preparation there is sure to be failure.", author: "Confucius"),
        PhilosopherQuote(text: "The superior man understands what is right; the inferior man understands what will sell.", author: "Confucius"),
        PhilosopherQuote(text: "The superior man is modest in his speech, but exceeds in his actions.", author: "Confucius"),
        PhilosopherQuote(text: "Respect yourself and others will respect you.", author: "Confucius"),
        PhilosopherQuote(text: "The superior man thinks always of virtue; the common man thinks of comfort.", author: "Confucius"),
        PhilosopherQuote(text: "The will to win, the desire to succeed, the urge to reach your full potential... these are the keys that will unlock the door to personal excellence.", author: "Confucius"),
        PhilosopherQuote(text: "When we see men of worth, we should think of equaling them; when we see men of a contrary character, we should turn inwards and examine ourselves.", author: "Confucius"),
        PhilosopherQuote(text: "The superior man acts before he speaks, and afterwards speaks according to his actions.", author: "Confucius"),
        PhilosopherQuote(text: "Learning without thought is labor lost; thought without learning is perilous.", author: "Confucius"),
        PhilosopherQuote(text: "The superior man makes the difficulty to be overcome his first interest; success only comes later.", author: "Confucius"),
        PhilosopherQuote(text: "The superior man is distressed by the limitations of his ability; he is not distressed by the fact that men do not recognize the ability that he has.", author: "Confucius"),
        PhilosopherQuote(text: "Better a diamond with a flaw than a pebble without.", author: "Confucius"),
        PhilosopherQuote(text: "The superior man is satisfied and composed; the mean man is always full of distress.", author: "Confucius"),
        PhilosopherQuote(text: "To see what is right and not to do it is want of courage.", author: "Confucius"),
        PhilosopherQuote(text: "The superior man does not, even for the space of a single meal, act contrary to virtue.", author: "Confucius"),
        PhilosopherQuote(text: "Fine words and an insinuating appearance are seldom associated with true virtue.", author: "Confucius"),
        PhilosopherQuote(text: "The superior man does not set his mind either for anything, or against anything; what is right he will follow.", author: "Confucius"),
        PhilosopherQuote(text: "The superior man is slow in his words and earnest in his conduct.", author: "Confucius"),
        PhilosopherQuote(text: "The superior man examines his heart, that there may be nothing wrong there.", author: "Confucius"),
        PhilosopherQuote(text: "The superior man is firm in the right way, and not merely firm.", author: "Confucius"),
        PhilosopherQuote(text: "The superior man has neither anxiety nor fear.", author: "Confucius"),
        PhilosopherQuote(text: "The superior man is quiet and calm, waiting for the appointments of heaven.", author: "Confucius"),
        PhilosopherQuote(text: "The superior man does what is proper to the station in which he is.", author: "Confucius"),
        PhilosopherQuote(text: "The superior man thinks of virtue; the small man thinks of comfort.", author: "Confucius"),
        PhilosopherQuote(text: "The superior man is catholic and not partisan.", author: "Confucius"),
        PhilosopherQuote(text: "The superior man is dignified, but does not fight.", author: "Confucius"),
        PhilosopherQuote(text: "The superior man is distressed by his want of ability.", author: "Confucius"),
        PhilosopherQuote(text: "The superior man is easy to serve, but difficult to please.", author: "Confucius"),
        PhilosopherQuote(text: "The superior man has a dignified ease without pride.", author: "Confucius"),
        PhilosopherQuote(text: "The superior man is correctly firm, and not firm merely.", author: "Confucius"),
        PhilosopherQuote(text: "The superior man seeks to perfect the admirable qualities of men.", author: "Confucius"),
        PhilosopherQuote(text: "The superior man understands righteousness; the inferior man understands profit.", author: "Confucius"),
        PhilosopherQuote(text: "The superior man thinks of virtue; the small man thinks of comfort.", author: "Confucius"),
        PhilosopherQuote(text: "The superior man helps the distressed, but does not add to the wealth of the rich.", author: "Confucius"),

        // Buddha quotes
        PhilosopherQuote(text: "Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment.", author: "Buddha"),
        PhilosopherQuote(text: "Peace comes from within. Do not seek it without.", author: "Buddha"),
        PhilosopherQuote(text: "Three things cannot be long hidden: the sun, the moon, and the truth.", author: "Buddha"),
        PhilosopherQuote(text: "Health is the greatest gift, contentment the greatest wealth, faithfulness the best relationship.", author: "Buddha"),
        PhilosopherQuote(text: "The mind is everything. What you think you become.", author: "Buddha"),
        PhilosopherQuote(text: "No one saves us but ourselves. No one can and no one may. We ourselves must walk the path.", author: "Buddha"),
        PhilosopherQuote(text: "Better than a thousand hollow words, is one word that brings peace.", author: "Buddha"),
        PhilosopherQuote(text: "In the end, only three things matter: how much you loved, how gently you lived, and how gracefully you let go of things not meant for you.", author: "Buddha"),
        PhilosopherQuote(text: "You will not be punished for your anger, you will be punished by your anger.", author: "Buddha"),
        PhilosopherQuote(text: "Holding on to anger is like grasping a hot coal with the intent of throwing it at someone else; you are the one who gets burned.", author: "Buddha"),
        PhilosopherQuote(text: "The root of suffering is attachment.", author: "Buddha"),
        PhilosopherQuote(text: "There is no path to happiness: happiness is the path.", author: "Buddha"),
        PhilosopherQuote(text: "You only lose what you cling to.", author: "Buddha"),
        PhilosopherQuote(text: "Your work is to discover your work and then with all your heart to give yourself to it.", author: "Buddha"),
        PhilosopherQuote(text: "Every morning we are born again. What we do today is what matters most.", author: "Buddha"),
        PhilosopherQuote(text: "The trouble is, you think you have time.", author: "Buddha"),
        PhilosopherQuote(text: "It is better to travel well than to arrive.", author: "Buddha"),
        PhilosopherQuote(text: "Nothing can harm you as much as your own thoughts unguarded.", author: "Buddha"),
        PhilosopherQuote(text: "A man is not called wise because he talks and talks again; but if he is peaceful, loving and fearless then he is in truth called wise.", author: "Buddha"),
        PhilosopherQuote(text: "Believe nothing, no matter where you read it, or who said it, unless it agrees with your own reason and your own common sense.", author: "Buddha"),
        PhilosopherQuote(text: "Those who are free of resentful thoughts surely find peace.", author: "Buddha"),
        PhilosopherQuote(text: "To understand everything is to forgive everything.", author: "Buddha"),
        PhilosopherQuote(text: "If you truly loved yourself, you could never hurt another.", author: "Buddha"),
        PhilosopherQuote(text: "Pain is certain, suffering is optional.", author: "Buddha"),
        PhilosopherQuote(text: "What you think, you become. What you feel, you attract. What you imagine, you create.", author: "Buddha"),
        PhilosopherQuote(text: "The past is already gone, the future is not yet here. There's only one moment for you to live.", author: "Buddha"),
        PhilosopherQuote(text: "To live a pure unselfish life, one must count nothing as one's own in the midst of abundance.", author: "Buddha"),
        PhilosopherQuote(text: "If anything is worth doing, do it with all your heart.", author: "Buddha"),
        PhilosopherQuote(text: "A jug fills drop by drop.", author: "Buddha"),
        PhilosopherQuote(text: "Happiness will never come to those who fail to appreciate what they already have.", author: "Buddha"),
        PhilosopherQuote(text: "The tongue like a sharp knife... Kills without drawing blood.", author: "Buddha"),
        PhilosopherQuote(text: "There is no fear for one whose mind is not filled with desires.", author: "Buddha"),
        PhilosopherQuote(text: "Even death is not to be feared by one who has lived wisely.", author: "Buddha"),
        PhilosopherQuote(text: "Let all bitterness, and wrath, and anger, and clamour, and evil speaking, be put away from you, with all malice.", author: "Buddha"),
        PhilosopherQuote(text: "Hatred does not cease through hatred at any time. Hatred ceases through love. This is an unalterable law.", author: "Buddha"),
        PhilosopherQuote(text: "However many holy words you read, however many you speak, what good will they do you if you do not act on upon them?", author: "Buddha"),
        PhilosopherQuote(text: "Just as a candle cannot burn without fire, men cannot live without a spiritual life.", author: "Buddha"),
        PhilosopherQuote(text: "Work out your own salvation. Do not depend on others.", author: "Buddha"),
        PhilosopherQuote(text: "The way is not in the sky. The way is in the heart.", author: "Buddha"),
        PhilosopherQuote(text: "Better than worshiping gods is obedience to the laws of righteousness.", author: "Buddha"),
        PhilosopherQuote(text: "In separateness lies the world's greatest misery; in compassion lies the world's true strength.", author: "Buddha"),
        PhilosopherQuote(text: "Teach this triple truth to all: A generous heart, kind speech, and a life of service and compassion are the things which renew humanity.", author: "Buddha"),
        PhilosopherQuote(text: "One moment can change a day, one day can change a life, and one life can change the world.", author: "Buddha"),
        PhilosopherQuote(text: "If we could see the miracle of a single flower clearly, our whole life would change.", author: "Buddha"),
        PhilosopherQuote(text: "True love is born from understanding.", author: "Buddha"),
        PhilosopherQuote(text: "You yourself, as much as anybody in the entire universe, deserve your love and affection.", author: "Buddha"),
        PhilosopherQuote(text: "Radiate boundless love towards the entire world.", author: "Buddha"),
        PhilosopherQuote(text: "A dog is not considered a good dog because he is a good barker. A man is not considered a good man because he is a good talker.", author: "Buddha"),
        PhilosopherQuote(text: "The whole secret of existence is to have no fear.", author: "Buddha"),
        PhilosopherQuote(text: "All that we are is the result of what we have thought.", author: "Buddha"),
        PhilosopherQuote(text: "An idea that is developed and put into action is more important than an idea that exists only as an idea.", author: "Buddha"),
        PhilosopherQuote(text: "Have compassion for all beings, rich and poor alike; each has their suffering.", author: "Buddha"),
        PhilosopherQuote(text: "It is better to conquer yourself than to win a thousand battles.", author: "Buddha"),
        PhilosopherQuote(text: "There are only two mistakes one can make along the road to truth; not going all the way, and not starting.", author: "Buddha"),
        PhilosopherQuote(text: "To keep the body in good health is a duty... otherwise we shall not be able to keep our mind strong and clear.", author: "Buddha"),
        PhilosopherQuote(text: "Words have the power to both destroy and heal. When words are both true and kind, they can change our world.", author: "Buddha"),
        PhilosopherQuote(text: "Your purpose in life is to find your purpose and give your whole heart and soul to it.", author: "Buddha"),
        PhilosopherQuote(text: "The only real failure in life is not to be true to the best one knows.", author: "Buddha"),
        PhilosopherQuote(text: "What we think, we become.", author: "Buddha")
    ]
    
    static var usedQuotes: Set<String> = []
    
    static func randomQuote() -> PhilosopherQuote {
        // If all quotes have been used, reset the used quotes
        if usedQuotes.count == quotes.count {
            usedQuotes.removeAll()
        }
        
        // Find a quote that hasn't been used yet
        let availableQuotes = quotes.filter { quote in
            !usedQuotes.contains(quote.text)
        }
        
        // Select a random quote from the available quotes
        guard let selectedQuote = availableQuotes.randomElement() else {
            // Fallback (though this should never happen)
            return quotes[0]
        }
        
        // Mark the quote as used
        usedQuotes.insert(selectedQuote.text)
        
        return selectedQuote
    }
} 